// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/kt/types.go

// Package kt is a generated GoMock package.
package kt

import (
	reflect "reflect"

	cluster "github.com/alibaba/kt-connect/pkg/kt/cluster"
	gomock "github.com/golang/mock/gomock"
)

// MockCliInterface is a mock of CliInterface interface.
type MockCliInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCliInterfaceMockRecorder
}

// MockCliInterfaceMockRecorder is the mock recorder for MockCliInterface.
type MockCliInterfaceMockRecorder struct {
	mock *MockCliInterface
}

// NewMockCliInterface creates a new mock instance.
func NewMockCliInterface(ctrl *gomock.Controller) *MockCliInterface {
	mock := &MockCliInterface{ctrl: ctrl}
	mock.recorder = &MockCliInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCliInterface) EXPECT() *MockCliInterfaceMockRecorder {
	return m.recorder
}

// Kubernetes mocks base method.
func (m *MockCliInterface) Kubernetes() cluster.KubernetesInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kubernetes")
	ret0, _ := ret[0].(cluster.KubernetesInterface)
	return ret0
}

// Kubernetes indicates an expected call of Kubernetes.
func (mr *MockCliInterfaceMockRecorder) Kubernetes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kubernetes", reflect.TypeOf((*MockCliInterface)(nil).Kubernetes))
}
