// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/kt/exec/types.go

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	kubectl "github.com/alibaba/kt-connect/pkg/kt/exec/kubectl"
	portforward "github.com/alibaba/kt-connect/pkg/kt/exec/portforward"
	ssh "github.com/alibaba/kt-connect/pkg/kt/exec/ssh"
	sshchannel "github.com/alibaba/kt-connect/pkg/kt/exec/sshchannel"
	sshuttle "github.com/alibaba/kt-connect/pkg/kt/exec/sshuttle"
	tun "github.com/alibaba/kt-connect/pkg/kt/exec/tun"
	gomock "github.com/golang/mock/gomock"
)

// MockCliInterface is a mock of CliInterface interface.
type MockCliInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCliInterfaceMockRecorder
}

// MockCliInterfaceMockRecorder is the mock recorder for MockCliInterface.
type MockCliInterfaceMockRecorder struct {
	mock *MockCliInterface
}

// NewMockCliInterface creates a new mock instance.
func NewMockCliInterface(ctrl *gomock.Controller) *MockCliInterface {
	mock := &MockCliInterface{ctrl: ctrl}
	mock.recorder = &MockCliInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCliInterface) EXPECT() *MockCliInterfaceMockRecorder {
	return m.recorder
}

// Kubectl mocks base method.
func (m *MockCliInterface) Kubectl() kubectl.CliInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kubectl")
	ret0, _ := ret[0].(kubectl.CliInterface)
	return ret0
}

// Kubectl indicates an expected call of Kubectl.
func (mr *MockCliInterfaceMockRecorder) Kubectl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kubectl", reflect.TypeOf((*MockCliInterface)(nil).Kubectl))
}

// PortForward mocks base method.
func (m *MockCliInterface) PortForward() portforward.CliInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PortForward")
	ret0, _ := ret[0].(portforward.CliInterface)
	return ret0
}

// PortForward indicates an expected call of PortForward.
func (mr *MockCliInterfaceMockRecorder) PortForward() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PortForward", reflect.TypeOf((*MockCliInterface)(nil).PortForward))
}

// SSH mocks base method.
func (m *MockCliInterface) SSH() ssh.CliInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SSH")
	ret0, _ := ret[0].(ssh.CliInterface)
	return ret0
}

// SSH indicates an expected call of SSH.
func (mr *MockCliInterfaceMockRecorder) SSH() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SSH", reflect.TypeOf((*MockCliInterface)(nil).SSH))
}

// SshChannel mocks base method.
func (m *MockCliInterface) SshChannel() sshchannel.Channel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SshChannel")
	ret0, _ := ret[0].(sshchannel.Channel)
	return ret0
}

// SshChannel indicates an expected call of SshChannel.
func (mr *MockCliInterfaceMockRecorder) SshChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SshChannel", reflect.TypeOf((*MockCliInterface)(nil).SshChannel))
}

// Sshuttle mocks base method.
func (m *MockCliInterface) Sshuttle() sshuttle.CliInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sshuttle")
	ret0, _ := ret[0].(sshuttle.CliInterface)
	return ret0
}

// Sshuttle indicates an expected call of Sshuttle.
func (mr *MockCliInterfaceMockRecorder) Sshuttle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sshuttle", reflect.TypeOf((*MockCliInterface)(nil).Sshuttle))
}

// Tunnel mocks base method.
func (m *MockCliInterface) Tunnel() tun.CliInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tunnel")
	ret0, _ := ret[0].(tun.CliInterface)
	return ret0
}

// Tunnel indicates an expected call of Tunnel.
func (mr *MockCliInterfaceMockRecorder) Tunnel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tunnel", reflect.TypeOf((*MockCliInterface)(nil).Tunnel))
}
