// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/kt/exec/tunnel/types.go

// Package tunnel is a generated GoMock package.
package tun

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCliInterface is a mock of CliInterface interface.
type MockCliInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCliInterfaceMockRecorder
}

// MockCliInterfaceMockRecorder is the mock recorder for MockCliInterface.
type MockCliInterfaceMockRecorder struct {
	mock *MockCliInterface
}

// NewMockCliInterface creates a new mock instance.
func NewMockCliInterface(ctrl *gomock.Controller) *MockCliInterface {
	mock := &MockCliInterface{ctrl: ctrl}
	mock.recorder = &MockCliInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCliInterface) EXPECT() *MockCliInterfaceMockRecorder {
	return m.recorder
}

// AddDevice mocks base method.
func (m *MockCliInterface) AddDevice() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDevice")
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevice indicates an expected call of AddDevice.
func (mr *MockCliInterfaceMockRecorder) AddDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevice", reflect.TypeOf((*MockCliInterface)(nil).AddDevice))
}

// AddRoute mocks base method.
func (m *MockCliInterface) AddRoute(cidr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoute", cidr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoute indicates an expected call of AddRoute.
func (mr *MockCliInterfaceMockRecorder) AddRoute(cidr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoute", reflect.TypeOf((*MockCliInterface)(nil).AddRoute), cidr)
}

// RemoveDevice mocks base method.
func (m *MockCliInterface) RemoveDevice() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDevice")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDevice indicates an expected call of RemoveDevice.
func (mr *MockCliInterfaceMockRecorder) RemoveDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevice", reflect.TypeOf((*MockCliInterface)(nil).RemoveDevice))
}

// SetDeviceIP mocks base method.
func (m *MockCliInterface) SetDeviceIP() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDeviceIP")
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDeviceIP indicates an expected call of SetDeviceIP.
func (mr *MockCliInterfaceMockRecorder) SetDeviceIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeviceIP", reflect.TypeOf((*MockCliInterface)(nil).SetDeviceIP))
}
