#!/bin/bash
echo "======== archive artifacts======="
cp LICENSE artifacts/kubectl-connect/LICENSE
ls -al artifacts/kubectl-connect
cd artifacts/kubectl-connect
rm -rf *.gz

tar zcvf kubectl-connect-darwin-amd64.tar.gz kubectl-connect-darwin-amd64 LICENSE
tar zcvf kubectl-connect-darwin-386.tar.gz kubectl-connect-darwin-386 LICENSE
tar zcvf kubectl-connect-linux-amd64.tar.gz kubectl-connect-linux-amd64 LICENSE
tar zcvf kubectl-connect-linux-386.tar.gz kubectl-connect-linux-386 LICENSE
tar zcvf kubectl-connect-windows-amd64.tar.gz kubectl-connect-windows-amd64.exe LICENSE
tar zcvf kubectl-connect-windows-386.tar.gz kubectl-connect-windows-386.exe LICENSE

tar zcvf kubectl-exchange-darwin-amd64.tar.gz kubectl-exchange-darwin-amd64 LICENSE
tar zcvf kubectl-exchange-darwin-386.tar.gz kubectl-exchange-darwin-386 LICENSE
tar zcvf kubectl-exchange-linux-amd64.tar.gz kubectl-exchange-linux-amd64 LICENSE
tar zcvf kubectl-exchange-linux-386.tar.gz kubectl-exchange-linux-386 LICENSE
tar zcvf kubectl-exchange-windows-amd64.tar.gz kubectl-exchange-windows-amd64.exe LICENSE
tar zcvf kubectl-exchange-windows-386.tar.gz kubectl-exchange-windows-386.exe LICENSE

tar zcvf kubectl-mesh-darwin-amd64.tar.gz kubectl-mesh-darwin-amd64 LICENSE
tar zcvf kubectl-mesh-darwin-386.tar.gz kubectl-mesh-darwin-386 LICENSE
tar zcvf kubectl-mesh-linux-amd64.tar.gz kubectl-mesh-linux-amd64 LICENSE
tar zcvf kubectl-mesh-linux-386.tar.gz kubectl-mesh-linux-386 LICENSE
tar zcvf kubectl-mesh-windows-amd64.tar.gz kubectl-mesh-windows-amd64.exe LICENSE
tar zcvf kubectl-mesh-windows-386.tar.gz kubectl-mesh-windows-386.exe LICENSE

tar zcvf kubectl-provide-darwin-amd64.tar.gz kubectl-provide-darwin-amd64 LICENSE
tar zcvf kubectl-provide-darwin-386.tar.gz kubectl-provide-darwin-386 LICENSE
tar zcvf kubectl-provide-linux-amd64.tar.gz kubectl-provide-linux-amd64 LICENSE
tar zcvf kubectl-provide-linux-386.tar.gz kubectl-provide-linux-386 LICENSE
tar zcvf kubectl-provide-windows-amd64.tar.gz kubectl-provide-windows-amd64.exe LICENSE
tar zcvf kubectl-provide-windows-386.tar.gz kubectl-provide-windows-386.exe LICENSE
