#!/bin/bash
export GO111MODULE on
GOARCH=amd64 GOOS=linux go build -o "artifacts/kubectl-connect/kubectl-connect-linux-amd64" ./cmd/kubectl-connect
GOARCH=386 GOOS=linux go build -o "artifacts/kubectl-connect/kubectl-connect-linux-386" ./cmd/kubectl-connect
GOARCH=amd64 GOOS=darwin go build -o "artifacts/kubectl-connect/kubectl-connect-darwin-amd64" ./cmd/kubectl-connect
GOARCH=386 GOOS=darwin go build -o "artifacts/kubectl-connect/kubectl-connect-darwin-386" ./cmd/kubectl-connect
GOARCH=386 GOOS=windows go build -o "artifacts/kubectl-connect/kubectl-connect-windows-386.exe" ./cmd/kubectl-connect
GOARCH=amd64 GOOS=windows go build -o "artifacts/kubectl-connect/kubectl-connect-windows-amd64.exe" ./cmd/kubectl-connect