#!/bin/bash
export GO111MODULE on

GOARCH=amd64 GOOS=linux go build -o "artifacts/kubectl-connect/kubectl-connect-linux-amd64" ./cmd/kubectl-connect
GOARCH=386 GOOS=linux go build -o "artifacts/kubectl-connect/kubectl-connect-linux-386" ./cmd/kubectl-connect
GOARCH=amd64 GOOS=darwin go build -o "artifacts/kubectl-connect/kubectl-connect-darwin-amd64" ./cmd/kubectl-connect
GOARCH=386 GOOS=darwin go build -o "artifacts/kubectl-connect/kubectl-connect-darwin-386" ./cmd/kubectl-connect
GOARCH=amd64 GOOS=windows go build -o "artifacts/kubectl-connect/kubectl-connect-windows-amd64.exe" ./cmd/kubectl-connect
GOARCH=386 GOOS=windows go build -o "artifacts/kubectl-connect/kubectl-connect-windows-386.exe" ./cmd/kubectl-connect

GOARCH=amd64 GOOS=linux go build -o "artifacts/kubectl-exchange/kubectl-exchange-linux-amd64" ./cmd/kubectl-exchange
GOARCH=386 GOOS=linux go build -o "artifacts/kubectl-exchange/kubectl-exchange-linux-386" ./cmd/kubectl-exchange
GOARCH=amd64 GOOS=darwin go build -o "artifacts/kubectl-exchange/kubectl-exchange-darwin-amd64" ./cmd/kubectl-exchange
GOARCH=386 GOOS=darwin go build -o "artifacts/kubectl-exchange/kubectl-exchange-darwin-386" ./cmd/kubectl-exchange
GOARCH=amd64 GOOS=windows go build -o "artifacts/kubectl-exchange/kubectl-exchange-windows-amd64.exe" ./cmd/kubectl-exchange
GOARCH=386 GOOS=windows go build -o "artifacts/kubectl-exchange/kubectl-exchange-windows-386.exe" ./cmd/kubectl-exchange

GOARCH=amd64 GOOS=linux go build -o "artifacts/kubectl-mesh/kubectl-mesh-linux-amd64" ./cmd/kubectl-mesh
GOARCH=386 GOOS=linux go build -o "artifacts/kubectl-mesh/kubectl-mesh-linux-386" ./cmd/kubectl-mesh
GOARCH=amd64 GOOS=darwin go build -o "artifacts/kubectl-mesh/kubectl-mesh-darwin-amd64" ./cmd/kubectl-mesh
GOARCH=386 GOOS=darwin go build -o "artifacts/kubectl-mesh/kubectl-mesh-darwin-386" ./cmd/kubectl-mesh
GOARCH=amd64 GOOS=windows go build -o "artifacts/kubectl-mesh/kubectl-mesh-windows-amd64.exe" ./cmd/kubectl-mesh
GOARCH=386 GOOS=windows go build -o "artifacts/kubectl-mesh/kubectl-mesh-windows-386.exe" ./cmd/kubectl-mesh

GOARCH=amd64 GOOS=linux go build -o "artifacts/kubectl-provide/kubectl-provide-linux-amd64" ./cmd/kubectl-provide
GOARCH=386 GOOS=linux go build -o "artifacts/kubectl-provide/kubectl-provide-linux-386" ./cmd/kubectl-provide
GOARCH=amd64 GOOS=darwin go build -o "artifacts/kubectl-provide/kubectl-provide-darwin-amd64" ./cmd/kubectl-provide
GOARCH=386 GOOS=darwin go build -o "artifacts/kubectl-provide/kubectl-provide-darwin-386" ./cmd/kubectl-provide
GOARCH=amd64 GOOS=windows go build -o "artifacts/kubectl-provide/kubectl-provide-windows-amd64.exe" ./cmd/kubectl-provide
GOARCH=386 GOOS=windows go build -o "artifacts/kubectl-provide/kubectl-provide-windows-386.exe" ./cmd/kubectl-provide
